### ISSUE TITLE
DX bug

### ISSUE THREAD

**Issue by mrGlasses** [CWBudde/DCEF3_Old#2]
Christian, Good Morning.

I've found a bug on the DX delphi version, I know it wasn't tested, it occurs in ceflib at line 9813, it tries to execute the cef_initialize procedure, but the program just shutdown, I really don't know how to fix it, if you want, I can send you a copy of my program, however, it just have a form and a TChromium.

Thanks for your attention.
Nickolas Guimarães

PS.: I also found a {$ifend} in cefvcl at line 33.

**Comment by mrGlasses** [comment]
- Please, disregard this issue, I've copied all items from the "package" folder and it works

**Comment by CWBudde** [comment]
Please note: this fork has retired and might get deleted in the future. Please consider to use the official repository by Henri Gourvest or my other fork (under the former name).
