### ISSUE TITLE
Fatal error trying to use the component on D7

### ISSUE THREAD

**Issue by duayres** [CWBudde/DCEF3_Old#3]
I was able to compile the BPL, but TChromium only runs for about 4 to 5 seconds, then debugger error. (Attached)
![image](https://cloud.githubusercontent.com/assets/7537810/15306972/50963450-1ba5-11e6-9982-0f607375ac37.png)
@hgourvest version of DCEF3 is working ok, but it does not support video playback (HTML5 playback)

**Comment by CWBudde** [comment]
This fork is an unofficial and private fork from old days. It's quite outdated now, especially given the fact that the official project is now also on GitHub and uses a later Chromium base.

For this reason the fork has been retired and might get deleted soon. I would suggest to either use Henri Gourvest's original repository or my other (sync'ed) fork under the former name. The changes I have made are rather of cosmetic nature, but there are also some minor fixes for XE7 (FMX doesn't compile as it should).
